default:
  just --list

install:

config:
  @rm -rf "{{home_dir()}}/.config/shell-utils/config.json"
  stow -t "{{home_dir()}}/.config/shell-utils" .

unset-config:
  stow -D -t "{{home_dir()}}/.config/shell-utils" .
