os := `cat /etc/os-release | grep "^NAME=" | cut -d "=" -f2 | tr -d '"'`

default:
  just --list

install-essential:
  #!/usr/bin/env bash
  if [ "{{os}}" = "Debian GNU/Linux" ] || [ "{{os}}" = "Ubuntu" ]; then
    sudo apt-get install build-essential libmysqlclient-dev
  elif [ "{{os}}" = "Arch Linux" ]; then
    sudo pacman -S --needed - < pacman.txt
  fi

install: install-essential
