global_packages_path := x'$HOME/.local/share/npm-globals'
rc_path := "${SU_RC_SOURCE_PATH:-$HOME/.config/util/setup}/npm"

install:
  mkdir -p {{global_packages_path}} {{rc_path}}
  npm i
  @just config

config:
  stow -t {{global_packages_path}} . --ignore='^config'
  stow -t {{rc_path}} config --no-folding

unset-config:
  stow -D -t {{global_packages_path}} . --ignore='^config'
  stow -D -t {{rc_path}} config --no-folding
